export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as VideoSection } from './VideoSection';
export { default as Section } from './Section';
export { default as PartnersSection } from './PartnersSection';
export { default as FeaturesSection } from './FeaturesSection';
export { default as BenefitsList } from './BenefitsList';
export { default as WaitlistSection } from './WaitlistSection';
export { default as Footer } from './Footer';
